#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


npm run compiler:check
staged_files=$(git diff --name-only --cached)
npm run literal:env:check $staged_files
files=$(printf " %s" "${staged_files[@]}")
npm run format:write:staged $files
git add .
